# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example
  # pod 'Firebase/Core'
  # pod 'GoogleTagManager', '~> 7.1'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :commit => 'ceb991adcd1addb3d089e542e2bfcfc74b316130'

end
